// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/devices/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/[id].patch').default>>>>
    }
    '/api/devices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/index.post').default>>>>
    }
    '/api/openapi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/openapi.get').default>>>>
    }
    '/api/reservations/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/[id].get').default>>>>
    }
    '/api/reservations/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/[id]/status.patch').default>>>>
    }
    '/api/reservations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reservations/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}