// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/27/2025, 2:10:20 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/Users/Zakhar/Documents/UNI/web_systems/lendrehab/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/plugins/**/*.{js,ts,mjs}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/composables/**/*.{js,ts,mjs}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/utils/**/*.{js,ts,mjs}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/Zakhar/Documents/UNI/web_systems/lendrehab/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;